language: go

matrix:
  include:
    - go: "1.11"
      env: GO111MODULE=on GOFLAGS=-mod=vendor
    - go: tip
  allow_failures:
    - go: tip

before_install:
  - make spellcheck

script:
  - make build
